### ISSUE TITLE
php error message on PicoRSS nextcloud after update

### ISSUE THREAD

**Issue by muranava** [HLSiira/PicoPlugins#1]
hi
after updating to Pico CMS for Nextcloud  1.0.14 i am getting an error message about php undefined index issue about the feed plugin - PicoRSS.php.
the plugin still seems to work though.
thx

**Comment by HLSiira** [comment]
What does the full error say?

**Comment by muranava** [comment]
hi full error:
---
{"reqId":"YD1udi6dCVx--5vQpRsB5AAAAIM","level":3,"time":"2021-03-01T22:45:10+00:00","remoteAddr":"my-ip-address","user":"xxxx","app":"PHP","method":"GET","url":"/index.php/apps/cms_pico/pico_proxy/rombuilder/","message":{"Exception":"Error","Message":"Undefined index: description at /var/www/nextcloud/apps/cms_pico/appdata_public/plugins/6UBP33ABJ1/PicoRSS/PicoRSS.php#28","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/cms_pico/appdata_public/plugins/6UBP33ABJ1/PicoRSS/PicoRSS.php","line":28,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/AbstractPicoPlugin.php","line":101,"function":"onConfigLoaded","class":"PicoRSS","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php","line":2788,"function":"handleEvent","class":"AbstractPicoPlugin","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php","line":430,"function":"triggerEvent","class":"Pico","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Pico.php","line":108,"function":"run","class":"Pico","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/PicoService.php","line":149,"function":"run","class":"OCA\\CMSPico\\Pico","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php","line":279,"function":"getPage","class":"OCA\\CMSPico\\Service\\PicoService","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Controller/PicoController.php","line":110,"function":"getPage","class":"OCA\\CMSPico\\Service\\WebsitesService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getPage","class":"OCA\\CMSPico\\Controller\\PicoController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"}
----

**Comment by HLSiira** [comment]
Ahh I see. It looks like you're missing a description in your Pico Config file.
```yml
## Basic
site_title: The Title                    # The title of your website
base_url: https://www.website.com        # Pico will try to guess its base URL, if this fails, override it here;

rewrite_url: ~                      # A boolean (true or false) indicating whether URL rewriting is forced
debug: true                            # Set this to true to enable Pico's debug mode
timezone: ~                         # Your PHP installation might require you to manually specify a timezone

description: A description of the website
tagline: A cool tagline
`

That's my theory anyway, I'm willing to be corrected that there is a bug in these plugins. I havne't spent too much time with them myself; just tried to get them to work and stop posting errors in my own logs lol.

Does that help at all?

**Comment by muranava** [comment]
hi okay tried adding description in the config, and i think error is not showing, thanks!
